<?php include('header.php');?>
  <body data-spy="scroll" data-target=".onpage-navigation" data-offset="60">
    <main>
      <div class="page-loader">
        <div class="loader">Loading...</div>
      </div>
              <?php include('menu.php');?>
                    <div class="main"><h1 class="text-center">Terms of Use</h1>
<div class="container">
<h3>Overview</h3>
<p>Welcome to the <?php echo $logo;?>. The <?php echo $logo;?> captures the passion, pride and energy of the high school experience by delivering live high school sports and events to family members and fans whenever they want, wherever they are. <?php echo $logo;?> events are available to subscribers online at www.<?php echo $logo;?>network.com as well as through the <?php echo $logo;?> branded iPhone and Android mobile apps.</p>
<p>The following Terms of Use, along with any additional terms and conditions that are referenced herein or that are presented in connection with a specific application, service or feature (collectively, &ldquo;Terms&rdquo;), and the <a href="./privacypolicy">Privacy Policy</a>, set forth the terms and conditions that apply to use of the <?php echo $logo;?> site and service (&ldquo;Service&rdquo;).&nbsp;&nbsp; Certain products and services available to you may require you to register and provide additional information to us, and in certain cases, to our third party providers, vendors and processors as a condition of application for and use of those products.&nbsp; For certain third party products, you also may be asked to accept the terms and policies of such provider. You should read all applicable terms and policies carefully to ensure you understand how a third party may use your information. &nbsp;Please read these Terms carefully.</p>
<p>These Terms are subject to change on occasion, so you should review these Terms from time to time, as you will be deemed to accept such changes through your continued use of the Service. We hope you enjoy your experience with the <?php echo $logo;?>.</p>
<h3>Acceptance of Terms of Use</h3>
<p>By using, visiting, or browsing the Service (whether through a web browser or one of our mobile applications), you accept and agree to be bound by these Terms. If you do not agree to these Terms, you cannot use the Service or any element thereof. We will also require you to accept these Terms when you create an account or become a member of the Service. Your use of our mobile applications is also subject to any additional terms and/or end user license agreements included with these applications.</p>
<h3>Changes to Terms of Use</h3>
<p>The <?php echo $logo;?> reserves the right, from time to time, with or without advance notice to you, to change these Terms in our sole and absolute discretion. The most current version of these Terms can be reviewed by visiting our website and clicking on "Terms of Use" located at the bottom of the pages. The most current version of the Terms will supersede all previous versions. The effective date of these Terms is stated below.</p>
<h3>Privacy Policy</h3>
<p>Any personally identifying information submitted through the Service is subject to our Privacy Policy. Please review our <a href="./privacypolicy">Privacy Policy</a> to understand our practices and procedures for personal information we collect through the Service.&nbsp; The date of any changes to our Privacy Policy will be noted at the bottom of the policy.&nbsp; As applicable, please also note the separate privacy policies for our vendors providing third party products and services through the Service. By using the Service, you are consenting to receive electronic communications from us related to the Service, your account and our operation and administration of the Service. You agree that any notice, agreements, disclosure or other communications that we send to you electronically will satisfy any legal communication requirements, including that such communications be in writing.&nbsp;</p>
<h3>Membership, Subscription and Billing</h3>
<p>The <?php echo $logo;?> provides video events and other digital content to visitors to our website and other user interfaces.&nbsp;&nbsp; The <?php echo $logo;?> reserves the right in its discretion and at any time (i) to deny any account creation request, (ii) to terminate your account and subscription to the Service, (iii) to remove any content from the Service, and/or (iv) to modify, interrupt, limit, suspend or discontinue, temporarily or permanently, the Service or any subscription or access to the Service. We are not liable to you or to any third party for any such modifications, suspensions or discontinuances of the Service or subscriptions or access.</p>
<h3><?php echo $logo;?> Membership</h3>
<p>Access to certain content on the Service may require an <?php echo $logo;?> membership, in which case you will be required to establish a valid email address and verified password in order to access this content. The <?php echo $logo;?> reserves the right, with or without notice to you, to determine which content is accessible either at no charge or via an <?php echo $logo;?> membership, in our sole and absolute discretion.</p>
<h3><?php echo $logo;?> Subscription</h3>
<p>Access to premium content on the Service may require a paid <?php echo $logo;?> subscription, in which case you will be required to provide certain information to register as an <?php echo $logo;?> member, establish a valid electronic payment method with the <?php echo $logo;?> (&ldquo;Payment Method&rdquo;), pay the applicable subscription fee and accept these Terms in order to access this content. As part of the registration process, you may be asked to verify that you are 13 years of age or older and that you have certain permissions from your parent or guardian if you are under the age of 18.&nbsp; If you are under 18, you must involve a parent or guardian in the registration process. Payment processing associated with a subscription may be handled by a third party payment processor. The current <?php echo $logo;?> subscription plans and rates are posted on the Service.&nbsp; Please note that prices and charges are subject to change as determined by <?php echo $logo;?> in its discretion.&nbsp; The <?php echo $logo;?> reserves the right to determine which content is accessible via an <?php echo $logo;?> subscription in our sole and absolute discretion.</p>
<h3>Account Information and Passwords</h3>
<p>As an <?php echo $logo;?> member, you will have access and control over your <?php echo $logo;?> account. Your control is exercised through use of your user name and password; therefore you should not reveal this information to anyone. You are solely responsible for keeping user name, password, Payment Method details and other codes and information pertaining to the Service and your account confidential and secure from unauthorized persons.&nbsp; Accounts are created for personal use only and may not be shared under any circumstances.&nbsp;</p>
<h3>Billing</h3>
<p>You can find the specific details regarding your subscription to the Service at any time by clicking on the <a href="./sign_in">My Account</a> link on the Service and using your user name and password to access this information on the Service.&nbsp; If you want to use a different Payment Method or if there is a change in Payment Method, such as your credit card validity or expiration date, you may edit your Payment Method information by clicking this link and using your user name and password to access your account information on the Service.&nbsp;&nbsp;</p>
<h3>Specialty Content Subscriptions</h3>
<p>In addition to our standard subscription offerings for the Service, we may offer special subscriptions that provide access to specially-produced, premium content or features that are provided on the Service from time to time. Should you wish to access any such special content, you will be required to register, enter a valid Payment Method and pay the applicable subscription fee as a condition of access to this content.&nbsp; Additional sign-up and payment options may be available to <?php echo $logo;?> subscribers through the <a href="./sign_in">My Account</a> link, as determined by the <?php echo $logo;?> in its discretion.&nbsp; The current <?php echo $logo;?> subscription plans and rates are posted on the Service. The <?php echo $logo;?> reserves the right to determine which content or features are accessible only as part of a special subscription or pass in our sole and absolute discretion.</p>
<h3>Authorization to Charge Your Payment Method</h3>
<p>By starting your <?php echo $logo;?> subscription, you expressly agree that the <?php echo $logo;?> is authorized, and may authorize its third party payment processor, to charge you a fee at the then current published rate for the Service using your selected Payment Method at the time of registration and upon any automatic renewal of your subscription to the Service in accordance with these Terms.&nbsp; Please note that prices and charges are subject to change as determined by the <?php echo $logo;?> in its discretion.&nbsp; As used in these Terms of Use, "billing" shall indicate either a charge or debit, as applicable, against your Payment Method.&nbsp; You may change your Payment Method as set forth in these Terms.</p>
<h3>Refunds</h3>
<p>Requests for refunds must be submitted to the <?php echo $logo;?> through the Customer Service link on the Service at <a href="./home">help.<?php echo $logo;?>network.com</a> or by email to <a href="mailto:customersupport@<?php echo $logo;?>network.com">Subscription Customer Support</a>&nbsp; <?php echo $logo;?> will honor any refund request for unused monthly subscriptions received within 30 days of the purchase date or the last renewal billing date. We may change the fees and charges in effect, or add new fees and charges from time to time, but we will give you advance notice of these changes by email.</p>
<h3>Auto-Renewal of Subscriptions</h3>
<p>The <?php echo $logo;?> Monthly Pass will renew automatically at the end of term unless and until you cancel your subscription or submit a request to Customer Service to terminate it. You must either cancel your subscription or change its renewal option to before it automatically renews each cycle in order to avoid billing of the next cycle&rsquo;s subscription fees to your Payment Method on file. Subscription fees are fully earned upon payment and may not be cancelled or refunded except as expressly permitted in these Terms. Please note that prices and charges are subject to change as determined by the <?php echo $logo;?> in its discretion.</p>
<p>To change the renewal option of your subscription from automatic renewal to manual renewal, visit <a href="./sign_in">My Account.</a></p>
<h3>Cancellation</h3>
<p>You may cancel your <?php echo $logo;?> subscription at any time. To cancel, go to <a href="./sign_in">My Account</a> and simply use your user name and password to access your account information on the Service. You can cancel any active subscriptions.&nbsp; Please note, however, that subscription fees are fully earned upon payment and may not be cancelled or refunded except as expressly permitted in these Terms.</p>
<h3>Right to Terminate</h3>
<p>We reserve the right to terminate or restrict your use of the Service, without notice, for any or no reason whatsoever.</p>
<h3>How Our Streaming Service Works</h3>
<p>The <?php echo $logo;?> is an online service providing its visitors, members, and subscribers with access to high school sports content streaming over the Internet to computers, mobile devices, and other Internet-connected devices. These devices are manufactured and sold by entities other than the <?php echo $logo;?>. We reserve the right in our sole and absolute discretion to make changes from time to time and without notice in how we operate and support the Service. Any description of how the Service works should not be considered a representation or obligation with respect to how the Service will always work. We reserve the right to modify, update and change the Service at any time and from time to time in our discretion.</p>
<p><strong>Availability:</strong> The availability of live and on demand content will change from time to time, and from device to device. The quality of the display of our content may vary from computer to computer, and device to device, and may be affected by a variety of factors, such as your location, the bandwidth available through and/or speed of your Internet connection. You are responsible for all Internet access connectivity and charges. Please check with your Internet provider for information on possible Internet data usage charges. The <?php echo $logo;?> makes no representations or warranties about the quality of your instant watching experience on your display.</p>
<p><strong>Personal Computer Requirements and Device Limitations:</strong> You may only use your account to watch the Service on one unique device at a time. We may terminate your account if we determine that you are using your account to access the Service from multiple devices concurrently or if we believe that you have shared your account credentials with other persons in violation of these Terms.</p>
<p>We do not warrant that any of the software used and or licensed in connection with the Service will be compatible with other third party software nor do we warrant that operation of the Service and the associated software will not damage or disrupt other software or hardware. Any issues related to the Service, including any system requirements, are covered and limited by these Terms. Please refer to the Disclaimers of Warranties and Limitations of Liability set forth in these Terms. In response to requests from content providers, or due to technical limitations, or for any reason in our sole and absolute discretion, and without prior notice to you, some or all of our content may not be watched, or may cease to be available for watching through the Service.</p>
<p>Disclaimers of Warranties and Limitations on Liability</p>
<p>THE SERVICE, INCLUDING OUR WEBSITE AND USER INTERFACES, AND ALL CONTENT AND SOFTWARE ASSOCIATED THEREWITH, AND ANY OTHER FEATURES OR FUNCTIONALITIES ASSOCIATED WITH THE SERVICE, ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND. WE AND OUR LICENSORS MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND WITH RESPECT TO THE SERVICE, OUR WEBSITE AND USER INTERFACES, OR ANY CONTENT AND SOFTWARE ASSOCIATED THEREWITH. THE <?php echo $logo;?> DOES NOT GUARANTEE, REPRESENT, OR WARRANT THAT YOUR USE OF THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, AND YOU AGREE THAT THE <?php echo $logo;?> MAY ELIMINATE OR OTHERWISE MODIFY ANY OR ALL ASPECTS OF THE SERVICE, INCLUDING FEATURES, WITHOUT COMPENSATION OR NOTICE TO YOU. THE <?php echo $logo;?> SPECIFICALLY DISCLAIMS LIABILITY FOR THE USE OF APPLICATIONS AND THE SERVICE SOFTWARE (INCLUDING THEIR CONTINUING COMPATIBILITY WITH THE SERVICE). Without limiting the foregoing, we and our licensors assume no liability or responsibility for any of the following: (i) errors or omissions in the content delivered by the Service, including the website and user interfaces; (ii) recommendations or advice of Customer Service; (iii) any failure or interruption in the availability of the Service and/or website or user interfaces, (iv) delivery and or display of any content contained on or through the Service, including the website and/or user interfaces; and (vii) any losses or damages arising from the use of the content provided on or through the Service, including website and/or user interfaces, including any losses or damages arising from downloading of related software, downloading and/or use of any other software, optical media discs or any conduct by users of the Service, including website and/or user interfaces. TO THE MAXIMUM EXTENT ALLOWABLE BY LAW, WE AND OUR LICENSORS DISCLAIM ALL REPRESENTATIONS AND WARRANTIES, INCLUDING, WARRANTIES OF MERCHANTABILITY, TITLE, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. In addition, we do not represent or warrant that the information accessible via our site is accurate, complete or current. We do not make any representations with respect to the content contained on video events from the Service or the descriptions of any video event content contained on our website and user interfaces. We do not represent or guarantee that your use of the Service will be free from interruption, loss, corruption, attack, viruses, interference, hacking, or other security intrusion and we disclaim any liability with respect thereto. No oral or written information or advice given by us or our authorized representatives, including Customer Service, shall create a warranty or otherwise constitute a representation binding upon the <?php echo $logo;?> or its affiliated parties.</p>
<p>IN NO EVENT SHALL THE <?php echo $logo;?> OR ITS SUBSIDIARIES OR ANY OF THEIR OWNERS, DIRECTORS, OFFICERS, EMPLOYEES OR LICENSORS BE LIABLE (JOINTLY OR SEVERALLY) TO YOU OR ANY PARTY FOR PERSONAL INJURY OR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES OR LOSS, WHETHER OR NOT ADVISED OF THE POSSIBILITY OF DAMAGE, AND ON ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE SERVICE, OUR WEBSITE AND USER INTERFACES, AND ALL CONTENT AND SOFTWARE ASSOCIATED THEREWITH, OR OTHERWISE RELATED TO THE SERVICE, INCLUDING ANY OPTICAL MEDIA DISCS, FEATURES OR FUNCTIONALITIES ASSOCIATED THEREWITH. IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL DAMAGES FOR LOSSES ARISING FROM THE USE OR INABILITY TO USE THE SERVICE, INCLUDING OUR WEBSITE AND USER INTERFACES, AND ALL CONTENT AND SOFTWARE ASSOCIATED THEREWITH (OTHER THAN AS MAY BE REQUIRED BY APPLICABLE LAW IN CASES INVOLVING PERSONAL INJURY) EXCEED THE AMOUNT OF YOUR MOST RECENT SUBSCRIPTION FEE. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. IF ANY APPLICABLE AUTHORITY HOLDS ANY PORTION OF THIS SECTION OR OTHER SECTIONS OF THESE TERMS OF USE, INCLUDING ANY PORTION OF THE PRIVACY POLICY, TO BE UNENFORCEABLE, THEN THOSE PORTIONS DEEMED UNENFORCEABLE SHALL BE SEVERED AND THE TERMS OF USE SHALL BE ENFORCED ABSENT THOSE PROVISIONS AND ANY LIABILITY WILL BE LIMITED TO THE FULLEST POSSIBLE EXTENT PERMITTED BY APPLICABLE LAW.</p>
<h3>Intellectual Property</h3>
<h3>Copyright</h3>
<p>The Service, including all content included on the website and/or user interfaces, or delivered to members as part of the Service, including, but not limited to, video events you can watch instantly, text, graphics, logos, designs, photographs, button icons, images, audio/video clips, digital downloads, data compilations, and software, are the property of the <?php echo $logo;?> or its licensors, and are protected by United States and international copyright, trade secret or other intellectual property laws and treaties. The compilation of all content, data and any software or other materials provided by the <?php echo $logo;?> on the Service, including the website and/or user interfaces, or in connection with the Service are the exclusive property of the <?php echo $logo;?> and its licensors and are protected by the copyright and trade secret laws in the territories in which the Service operates and by international treaty provisions. Neither the Service content nor software may be reproduced for any purpose whatsoever.&nbsp; Any use of the Service shall be in strict accordance with these Terms. You agree not to decompile, reverse engineer or disassemble any software or other products or processes accessible through the Service, not to insert any code or product or manipulate the content of the Service in any way, and not to use any data mining, data gathering or extraction method. The <?php echo $logo;?> reserves the right to terminate your membership hereunder if the <?php echo $logo;?>, in its sole and absolute discretion, believes that you are in violation of these Terms or applicable law or that you are otherwise infringing or violating the <?php echo $logo;?>&rsquo;s proprietary rights in and to the Service and/or any elements thereof.&nbsp; The <?php echo $logo;?> does not promote, foster or condone the copying of content or video events of any party or any other infringing activity. The use of the Service, including video events, tools and features made available to you by us through the Service, is solely for your personal and non-commercial use. For the sake of clarity, your use of any feature on the Service that enables clipping and sharing of content from the Service and/or use of that content may be implemented only through the tools provided for such feature without any copying of the content, and is strictly for personal use and may not be used to distribute, syndicate or share with others via any commercial site, service or page.&nbsp; Other terms may be posted with and apply to use of such features.&nbsp; Please see Claims of Copyright Infringement below for instructions for notifying us of the presence of any allegedly infringing content of the Service, including any on the website and/or user interfaces.&nbsp;</p>
<h3>Video Player</h3>
<p>You may not modify, interfere with, enhance, remove, or otherwise alter in any way any portion of the Video Player, or any of the Video Player&rsquo;s underlying technology, any digital rights management mechanism, device, or other content protection or access control measure incorporated into the Video Player. This restriction includes, without limitation, disabling, modifying, reverse engineering, interfering with or otherwise circumventing the Video Player in any manner that enables users to view the Content without: (i) visibly displaying both the Video Player and all surrounding elements (including the graphical user interface, any advertising, copyright notices, and trademarks) of the webpage where the Video Player is located; and (ii) having full access to all functionality of the Video Player, including, without limitation, all video quality and display functionality and all interactive, elective or click-through advertising functionality.&nbsp; Other restrictions and terms set forth in these Terms applicable to the <?php echo $logo;?> software shall apply to the Video Player.</p>
<h3>Trademarks</h3>
<p>The <?php echo $logo;?> is a registered trademark of the <?php echo $logo;?>, LLC. The <?php echo $logo;?> logo and <?php echo $logo;?>Network.com are trademarks or service marks of <?php echo $logo;?>, LLC. The Service, website and user interfaces, including but not limited to its graphics, logos, page headers, button icons, look and feel, scripts and the Service names constitute trade dress of the <?php echo $logo;?> LLC. The trademarks, service marks and trade dress of the <?php echo $logo;?> may not be used or reproduced without prior written approval from the <?php echo $logo;?> and may not be used in connection with any product or service that is not affiliated with the <?php echo $logo;?>, in any manner that is likely to cause confusion among customers, in any manner that dilutes the rights of the <?php echo $logo;?>, or in any manner that disparages or discredits the <?php echo $logo;?> or its licensors. Other trademarks that appear on the <?php echo $logo;?> website and user interfaces are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by the <?php echo $logo;?>. Any images of persons or personalities contained on the <?php echo $logo;?> website and user interfaces are not an indication or endorsement of the <?php echo $logo;?> or any particular product or the Service unless otherwise indicated.&nbsp; Please be aware that persons depicted in such images may have additional right in such images that require consent and/or payment for any use outside the Service.</p>
<h3>Use of Information Submitted</h3>
<p>By submitting comments, information, ideas, concepts, reviews, or techniques or any other material contained in any communication you may send to us ("Materials"), including responses to questionnaires or through postings to the Service, including the <?php echo $logo;?> website and user interfaces, you grant us a perpetual, transferrable, royalty-free license, with right to sublicense, in and to the Materials for use in our discretion via any means, media and format now known or hereafter devised without any obligation to you, including, but not limited to, use in developing, manufacturing and marketing new products and services and in creating, supplementing, modifying and/or improving the Service.&nbsp; Further, you hereby waive any claim or claims against the <?php echo $logo;?>, its affiliates, licensors and successors-in-interest regarding use of such Materials.&nbsp; Your represent and warrant to us that any and all Materials submitted by you is and will be original to you and does not or will not infringe or violate the rights of any party.&nbsp;</p>
<h3>Customer Service</h3>
<p>If you need assistance with your account, you may find answers and reach Customer Service at any time through the Help Site located at <a href="./home">help.<?php echo $logo;?>network.com</a> or by email to <a href="mailto:customersupport@<?php echo $logo;?>network.com">Subscription Customer Support</a>&nbsp;. Through these resources, you will find the answers to many frequently asked questions and information.&nbsp; The Disclaimers of Warranties and Limitations of Liability and other applicable provisions set forth in these Terms expressly apply to the use of Customer Service. We may utilize the services of third parties in providing you Customer Service support and additional terms may apply.</p>
<h3>Your Conduct in Accessing the Service</h3>
<p>The <?php echo $logo;?> content features students and certain content is produced by participating schools and their students.&nbsp; As such, the content and the Service are intended to be suitable for a general audience, including students and their friends and family members.&nbsp; The <?php echo $logo;?> requires an appropriate level of decorum in your use and sharing of our content, similar to what you would encounter by actually visiting a high school event.</p>
<p>By accessing the Service, including the website and/or user interfaces, you agree to use the Service, including all features and functionalities associated therewith, the website and/or user interfaces and all content and software associated therewith in accordance with these Terms and all applicable laws, rules and regulations, including public performance limitations or other restrictions on use of the Service or content therein. You agree not to upload, post, e-mail or otherwise send or transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment associated with the Service.&nbsp; You also agree not to impersonate any other person or imply any affiliation with the <?php echo $logo;?> in connection with your use of the Service, conduct yourself in a vulgar or offensive manner while using the Service, or use the Service for any unlawful purpose.</p>
<p>You agree that all of the foregoing restrictions, as well as the other applicable restrictions set forth in these Terms, apply not only to the Service, but also to the servers and networks connected to any portions of the Service whether operated by the <?php echo $logo;?> or third parties (&ldquo;Networks&rdquo;).&nbsp; You agree not to interfere with Networks, violate any of the procedures, policies or regulations applicable to Networks, use Networks in a way that harms or impairs anyone else&rsquo;s use of Networks, use Networks to gain unauthorized access to any service, data, account or other networks, use Networks to falsify any protocol or email header information (e.g., &ldquo;spoofing&rdquo;), use Networks to send &ldquo;spam&rdquo; (i.e., unsolicited bulk email or commercial messages) or items of a destructive or deceptive nature, or remove, modify, or tamper with any regulatory or legal notice or link that is incorporated into Networks.</p>
<h3>Limitations on Use</h3>
<p>You must be 13 years of age or older to become a member of the Service and meet other applicable requirements as set forth in these Terms.&nbsp; Individuals under the age of 18 must also obtain the permission of a parent or guardian who must review and accept these Terms personally and on behalf of such individuals to become a member of the Service. Unless otherwise specified, the Service, and any content viewed through the Service, are for your personal and non-commercial use only and we grant you a limited, non exclusive, non transferable, license to access the Service solely for that purpose. No right, title or ownership interest in or to the Service or any elements thereof shall be transferred to you.</p>
<p>You may not download (other than through page caching necessary for personal use, or as otherwise expressly permitted by these Terms of Use), modify, copy, distribute, transmit, display, perform, reproduce, duplicate, publish, license, create derivative works from, or offer for sale any content, data or other information contained on, or obtained from or through, the Service.</p>
<p>The <?php echo $logo;?> does not promote, foster or condone the unauthorized copying of digitally delivered content, or any other infringing activity. You may not circumvent, remove, alter, deactivate, degrade or thwart any of the content protections in the Service. You may not purchase search terms or use any meta tags or any other "hidden text" utilizing the <?php echo $logo;?> name or trademarks. Any unauthorized use of the Service or its contents will terminate the limited license granted by us and will result in the cancellation of your membership or subscription.</p>
<h3>Claims of Copyright Infringement</h3>
<p>It is the policy of the <?php echo $logo;?> to respect the intellectual property rights of others. The <?php echo $logo;?> does not permit or condone the unauthorized reproduction or distribution of video events or other copyrighted content. If you believe your work has been reproduced or distributed in a way that constitutes copyright infringement or are aware of any infringing material available through the Service, please notify us via email at <a href="mailto:customersupport@hssports.com">Subscription Customer Support</a>.&nbsp; You may be asked to provide additional information and follow additional procedures for us to act on your complaint.&nbsp;</p>
<h3>Dispute Resolution</h3>
<p>The parties specifically agree to submit any controversy or claim arising out of or relating to this agreement, the Service, or any alleged breach of this agreement, or any other controversy or claim between the parties, solely and exclusively to arbitration administered by the American Arbitration Association (&ldquo;AAA&rdquo;) in accordance with its Commercial Arbitration Rules.&nbsp; Claims seeking relief on a class-wide or consolidated basis rather than on an individual basis may be brought exclusively on an individual basis in arbitration and the parties specifically waive any right to bring any claims between themselves in court on a consolidated or class-action basis.&nbsp; The validity of this arbitration clause is governed by the Federal Arbitration Act, 9 U.S.C. &sect; 1 et seq.&nbsp; The following provisions govern the conduct of the arbitration and any award therefrom:</p>
<ol>
<li>The notice of intention to arbitration (&ldquo;demand&rdquo;) must be filed with the AAA regional office to be assigned to Atlanta, Georgia.&nbsp; All in-person hearings will be held in Atlanta, Georgia.</li>
<li>Claims shall be heard by a single arbitrator, unless the claim amount exceeds $2,000,000, in which case the dispute shall be heard by a panel of three arbitrators. The arbitrator(s) must be qualified in matters relating to programming distribution and subscription agreements.&nbsp;</li>
<li>Each party will, upon written request of the other party, promptly provide the other with copies of all relevant documents. The arbitrator(s) will decide any objections to production of evidence.&nbsp; The arbitrator(s) may not allow, direct or authorize any other discovery.</li>
<li>The arbitrator(s) must issue the award within four (4) months of the filing of the demand, and the arbitrator(s) must agree to comply with this schedule before accepting appointment. This time limit may be extended by the arbitrator(s) only for good cause shown or by mutual agreement of the parties.</li>
<li>The arbitrator(s) have no authority to award punitive damages, consequential damages, or other damages not measured by the prevailing party&rsquo;s actual damages, except as may be required by statute. The arbitrator(s) may award only monetary damages and may not include in the award any injunction or direction to a party other than to pay a monetary amount. The arbitrator(s) must include reasonable attorneys&rsquo; fees to be paid to the prevailing party. The arbitrator(s)&rsquo; award will include a reasoned opinion.</li>
<li>The parties specifically agree that failure or refusal of any party to pay its required share of the deposits for arbitrator compensation or administrative charges as directed by the AAA constitutes a waiver by that party to present evidence or cross-examine witnesses.&nbsp; In that event, the other party will present evidence and legal argument only as the arbitrator(s) may require for the making of an award.&nbsp; The waiver of the right to present evidence does not allow for a default judgment against the non-paying party.</li>
<li>Except as may be required by law, neither a party nor an arbitrator may disclose the existence, content, or results of any arbitration hereunder without the prior written consent of both parties.</li>
<li>The award may be appealed pursuant to the AAA&rsquo;s Optional Appellate Arbitration Rules (&ldquo;Appellate Rules&rdquo;) and as a result, the award is not final until after the time for filing the notice of appeal pursuant to the Appellate Rules has expired.&nbsp; Appeals must be initiated within thirty (30) days of receipt of an award, as defined by Rule A-3 of the Appellate Rules, by filing a Notice of Appeal with any AAA office.&nbsp; If no appeal has been filed, then judgment on the award may be taken in any court of competent jurisdiction.&nbsp; If an appeal is filed, then following the appeal process, the decision rendered by the appeal tribunal may be entered in any court having jurisdiction thereof.</li>
</ol>
<h3>Governing Law and Severability</h3>
<p>These Terms shall be governed by and construed in accordance with the laws of the State of Georgia without regard to conflict of laws provisions. You consent to the exclusive jurisdiction and venue of any court of competent jurisdiction in Atlanta, Georgia, with respect to any dispute arising out of or relating to these Terms of Use. If any provision or provisions of these terms shall be held to be invalid, illegal, unenforceable or in conflict with the law of any jurisdiction, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired thereby, and shall remain in full force and effect.</p>
</div>

<?php include('footer.php');?>